"""Initial schema

Revision ID: 5640303a7c6c
Revises: 07c33c995d50
Create Date: 2026-09-12 11:57:32.390099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5640303a7c6c'
down_revision: Union[str, None] = '07c33c995d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_accounts')
    op.drop_table('alert_transactions')
    op.drop_index(op.f('ix_alert_rule_results_alert_id'), table_name='alert_rule_results')
    op.drop_table('alert_rule_results')
    op.add_column('alerts', sa.Column('transaction_id', sa.UUID(), nullable=False))
    op.add_column('alerts', sa.Column('risk_level', sa.String(length=50), nullable=False))
    op.add_column('alerts', sa.Column('triggered_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('alerts', 'risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'alerts', ['transaction_id'])
    op.create_foreign_key(None, 'alerts', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='unique')
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'risk_score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('alerts', 'triggered_rules')
    op.drop_column('alerts', 'risk_level')
    op.drop_column('alerts', 'transaction_id')
    op.create_table('alert_rule_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score_contribution', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('alert_rule_results_alert_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_rule_results_pkey'))
    )
    op.create_index(op.f('ix_alert_rule_results_alert_id'), 'alert_rule_results', ['alert_id'], unique=False)
    op.create_table('alert_transactions',
    sa.Column('alert_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('alert_transactions_alert_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('alert_transactions_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('alert_id', 'transaction_id', name=op.f('alert_transactions_pkey'))
    )
    op.create_table('alert_accounts',
    sa.Column('alert_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('alert_accounts_account_id_fkey')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('alert_accounts_alert_id_fkey')),
    sa.PrimaryKeyConstraint('alert_id', 'account_id', name=op.f('alert_accounts_pkey'))
    )
    # ### end Alembic commands ###
