"""Add hashed_password to investigators

Revision ID: 5f17fa0deb51
Revises: a052c7b05624
Create Date: 2026-09-12 12:28:19.374160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f17fa0deb51'
down_revision: Union[str, None] = 'a052c7b05624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigators', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigators', 'hashed_password')
    # ### end Alembic commands ###
